---
# tasks file for igami.zigbee2mqtt

- name: Install zigbee2mqtt dependencies.
  package:
    name:
      - git
      - nodejs

- name: Create zigbee2mqtt user.
  user:
    name: "{{ zigbee_user }}"
    groups: "{{ zigbee_user_groups }}"
    append: "{{ zigbee_user_append }}"
    system: yes
    create_home: no
    shell: /usr/sbin/nologin

- name: Create zigbee2mqtt directory.
  file:
    path: "{{ zigbee_dir }}"
    state: directory
    owner: "{{ zigbee_user }}"

- name: Clone zigbee2mqtt repository.
  git:
    repo: "{{ zigbee_repository }}"
    depth: 1
    dest: "{{ zigbee_dir }}"
    update: no
  become: yes
  become_user: "{{ zigbee_user }}"
  notify: Restart zigbee2mqtt
  register: repo

- name: Install zigbee2mqtt via npm.
  npm:
    path: "{{ zigbee_dir }}"
  become: yes
  become_user: "{{ zigbee_user }}"
  notify: Restart zigbee2mqtt
  when: repo.changed

- name: Generate network key.
  template:
    src: network_key.yaml.j2
    dest: "{{ zigbee_dir }}/data/network_key.yaml"
    owner: "{{ zigbee_user }}"
    group: "{{ zigbee_user }}"
    mode: 0600
    force: "{{ zigbee_generate_new_network_key }}"
  notify: Restart zigbee2mqtt

- name: Install configuration template.
  template:
    src: configuration.yaml.j2
    dest: "{{ zigbee_dir }}/data/configuration.yaml"
    owner: "{{ zigbee_user }}"
  notify: Restart zigbee2mqtt

- name: Install systemd service template.
  template:
    src: zigbee2mqtt.service.j2
    dest: /etc/systemd/system/zigbee2mqtt.service
    owner: "{{ zigbee_user }}"
  notify: Restart zigbee2mqtt

- name: Start zigbee2mqtt service.
  systemd:
    name: zigbee2mqtt
    enabled: true
    state: started
    daemon_reload: true
